# Generated by Django 4.2.6 on 2024-05-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_textpage_is_generic_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='last_name',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Название компании'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='phone',
            field=models.CharField(max_length=24, verbose_name='Телефон'),
        ),
    ]
