# Generated by Django 4.2.6 on 2024-05-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_feedbackrequest_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackrequest',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='feedbackrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=24, verbose_name='Телефон'),
        ),
    ]
