# Generated by Django 5.1.1 on 2024-09-05 12:53

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_feedbackrequest_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', ckeditor.fields.RichTextField(blank=True, verbose_name='Контент')),
                ('show_in_sitemap', models.BooleanField(default=True, verbose_name='Показывать в карте сайта')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='OG Title')),
                ('og_description', models.TextField(blank=True, max_length=2000, verbose_name='OG Description')),
                ('og_type', models.CharField(blank=True, max_length=200, verbose_name='OG Type')),
                ('og_type_pb_time', models.DateField(default=datetime.date.today, verbose_name='Время публикации')),
                ('og_type_author', models.CharField(blank=True, max_length=200, verbose_name='OG author')),
                ('seo_h1', models.CharField(blank=True, max_length=200, verbose_name='H1')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='Title')),
                ('seo_description', models.CharField(blank=True, max_length=500, verbose_name='Description')),
                ('seo_keywords', models.CharField(blank=True, max_length=500, verbose_name='Keywords')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('image', models.FileField(blank=True, upload_to='articles/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='feedbackrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='feedbackrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
