# Generated by Django 5.1.1 on 2024-09-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_article_remove_feedbackrequest_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publish_at',
            field=models.DateTimeField(blank=True, help_text='Используется для отложенного постинга', null=True, verbose_name='Дата публикации'),
        ),
    ]
